### ISSUE TITLE
Missing Ticker.h

### ISSUE THREAD

**Issue by sudoMakeThisSecure** [AlbertGBarber/Infinity-Dodecahedron#2]
Hay mate, your code requires a Ticker.h file in "#include <Ticker.h>", but cant find it anywhere? Maybe it was part of an old version?

**Comment by AlbertGBarber** [comment]
Ticker is a library included in the Arduino Esp8266 boards package. The package is required to compile any Esp8266 code. Compilation is currently working for me. If is not for you, please check/reinstall the Esp boards package.
